### ISSUE TITLE
interactionID should be harmonized with activation triggering input events

### ISSUE THREAD

**Issue by annevk** [WICG/event-timing#105]
https://html.spec.whatwg.org/#activation-triggering-input-event

Seems bad to have multiple sources of what is considered a user interaction.

**Comment by npm1** [comment]
It seems hard to reconcile the two. For instance we care about keyboard events, and those are not activation triggering.

**Comment by annevk** [comment]
Well, I think in implementations they are. See https://github.com/whatwg/html/issues/3849.

**Comment by npm1** [comment]
It sounds like maybe some, but not all. I don't think we'd want to special-case the `Esc` key for performance measurement whereas it makes sense to consider it different for the user activation scenario. So although I agree there is a wide overlap, I think they're not quite the same.

**Comment by npm1** [comment]
Ok to close this?

**Comment by annevk** [comment]
Yeah I guess so, though I'm still a bit wary about maintaining a generic list like this in such a specific document. Is the plan to uplift this to UI Events?

**Comment by npm1** [comment]
It is only used here for now, but we can move it to UI Events if anything to make it more discoverable. Filed https://github.com/WICG/event-timing/issues/114
