### ISSUE TITLE
Should we spec the buffer related APIs somewhere?

### ISSUE THREAD

**Issue by maxlgu** [WICG/event-timing#2]
As we will add these APIs, should they be specced here? 
void clearEventTimings();
void setEventTimingBufferMaxSize(unsigned long maxSize);
attribute EventHandler oneventtimingbufferfull;

**Comment by npm1** [comment]
We do not intend to have these. We want to expose buffered entries via the buffered flag in PerformanceObserver, which is being worked on in PerformanceTimeline.
