### ISSUE TITLE
Scrolling Event

### ISSUE THREAD

**Issue by AbigailMonday** [WICG/event-timing#23]
We would like to have the ability to monitor our scrolling performance.

Our use-case involves rendering a big amount of dynamic data. We use windowing to only render the relevant data each time, so scrolling causes newly-presented data to be rendered.
Scrolling events will be very helpful to monitor performance in this case.

**Comment by npm1** [comment]
Thanks for the feedback! We do intend to add measurements to look at scrolling performance in a future version of the API. In particular, I think it would be useful to expose cases in which the scrolling takes a long time to render or blocks javascript execution.

**Comment by npm1** [comment]
By the way I imagine this is related to actual scroll-gesture-to-pixel performance and not the performance of the `scroll` event itself, right? In that case we plan to solve performance measuring of that via the Frame Timing API. You can see an explainer at https://docs.google.com/document/d/1t3A56iTN01ReEELJ18_jLYrvc13L3hDTXWK46AafKwE/edit, I'm closing this for now but let me know if this does not address your issue!
