### ISSUE TITLE
Non-normative section has a must

### ISSUE THREAD

**Issue by domenic** [WICG/event-timing#26]
> The duration attribute’s getter must return...

You can have Bikeshed check this for you if you wrap the section in `<div class="non-normative">` and add `Complain About: accidental-2119` metadata.

**Comment by domenic** [comment]
Same for `cancelable` a bit further down.

Otherwise, overall I like that section and how it very clearly describes things in a helpful way, while also being very clear the normative work happens elsewhere.

**Comment by npm1** [comment]
Is this just a matter of replacing 'must' with another word without normative meaning, like 'should'? Oh, or I can simply remove 'must' altogether and instead say:

`The duration attribute’s getter returns...`

**Comment by domenic** [comment]
Yeah, turning it into a "statement of fact" with "returns", like you do for the rest of the attributes, works great.
