### ISSUE TITLE
Which events to capture? The current setup is a bit strange.

### ISSUE THREAD

**Issue by domenic** [WICG/event-timing#29]
First, https://wicg.github.io/event-timing/#sec-events-exposed is a bit confusing because it never mentions the isTrusted requirement. So I was immediately wondering about `new MouseEvent("asdf", ...)` or `new CustomEvent("mousedown")`. But the processing model is clearer.

The processing model is a bit strange though because of its switching between working on event names and working on event classes (interfaces). Although I guess the setup may give the technically correct result, it feels fragile. Is there a way to consolidate around only a single technique for testing the event type? I would suggest event names, if I were to choose.

Finally, it's also worth noting that page script can dispatch isTrusted click events using the `.click()` method. Is capturing these intentional? That's worth writing tests for, certainly.

**Comment by npm1** [comment]
@tdresser do you think it would be reasonable to change the check so we always use event names? Will need to enumerate all of them explicitly.

Also, if .click() produces a trusted click event, we may want to exclude those... Most will have pointerdown or mousedown anyways. WDYT?

**Comment by tdresser** [comment]
Good point. We should exclude those.

**Comment by tdresser** [comment]
Always using event names SGTM.

**Comment by npm1** [comment]
I'm testing this in Chrome and .click() seems to produce an event for which isTrusted=false... Also this is a bit confusing because it implies .click() is an exception but behaves the same as dispatchEvent()?
https://dom.spec.whatwg.org/#dom-event-istrusted

**Comment by domenic** [comment]
I'm sorry, I was totally wrong. .click() is wierd because it causes a "UA-generated" click event, but *doesn't* set isTrusted to true. This weirdness actually works in our favor for this API.

Sorry for wasting time on that. I remembered click() was weird, but was totally incorrect about how.

**Comment by npm1** [comment]
No worries, adding a test seems like a good idea, we didn't have one.

**Comment by npm1** [comment]
Fixed by https://github.com/WICG/event-timing/pull/39
