### ISSUE TITLE
Use implements to check type

### ISSUE THREAD

**Issue by domenic** [WICG/event-timing#30]
Although #29 may make this obsolete, I'll note that

> If event is NOT a MouseEvent, PointerEvent TouchEvent, KeyboardEvent, WheelEvent, InputEvent, or CompositionEvent,

can be made precise using the relatively-new https://heycam.github.io/webidl/#implements (and cross-linking to it).

**Comment by npm1** [comment]
Yup, obsolete now! It seems that it's not strictly necessary to link to the concept:

> Specifications may reference the concept "object implements interface" in various ways, including "object is an interface object".
