### ISSUE TITLE
"Queuing other entries" section is confusing

### ISSUE THREAD

**Issue by domenic** [WICG/event-timing#34]
I'm unsure why the "create an event timing entry" algorithm is in this section, or when it would ever be used. The paragraph previous to it talks about how the user agent cannot skip using the event dispatch algorithm, but then it gives me an algorithm which is meant to be used "outside of the event dispatch algorithm".

But, this "create an event timing entry" algorithm is never actually called by anyone. That's confusing.

Could this whole section be replaced by saying something like "previously, user agents could skip the entire event dispatch algorithm in some cases. With this spec, that is no longer possible entirely, because they need to record the event timing. The optimizations will need to be cleverer"? (Such as, for example, boiling the entire event dispatch algorithm down to just the steps of "create an event timing entry". But I don't think you need to give people a pre-optimized algorithm in the spec.)

**Comment by npm1** [comment]
Yep, this is hand-wavy :( The previous paragraph says that the user agent cannot skip using the event dispatch algorithm for the firstInput entry. But we still want to allow skipping the event dispatch algorithm sometimes. In other words, it is still possible for a user agent to sometimes skip event dispatch, even though not skipping it could have produced an EventTiming entry. It is not possible to do so when it would have produced a firstInput entry.

**Comment by domenic** [comment]
What is the observable difference between:

- (A) Allowing the user agent to skip event dispatch, in which case it needs to use "create an event timing entry" algorithm
- (B) Omitting this section entirely?

Perhaps as a more fundamental question, am I understanding the section right that (A) is what it's aiming for? Nothing ever calls "create an event timing entry", so I'm not so sure...

**Comment by npm1** [comment]
Yes that is correct, (A) is what this section is aiming to cover. Do you think this is not needed? We could remove it, although a benefit of having this section is that we are indicating how to differentiate between these entries and entries that would go through event dispatch (`processingStart` and `processingEnd` will both be 0).

**Comment by domenic** [comment]
Oh, I missed that they would both be zero. I will try to think on this harder.

**Comment by domenic** [comment]
So here is what I would suggest. Update "Modifications to the DOM specification" section with an epilogue something like the following.

> If this algorithm would only cause observable effects through the steps that initialize and finalize event timing, and the event is not the first input (TODO: define this more rigorously somehow), then the user agent may instead either do nothing, or  replace the entirety of the event dispatch algorithm with the  [=create a skipped event dispatch event timing entry=] algorithm:

Here, "create a skipped event dispatch event timing entry" is the current spec's "create an event timing entry", but it should be rephrased to take the same inputs as the event dispatch algorithm.

You should also call out briefly in a note that the important observable difference is 0 for both values, since that's a bit easy to miss.

How does this sound? Did I correctly capture the intention here? (Maybe the "do nothing" option was not intended?)

**Comment by npm1** [comment]
The intention does seem correct. I still find that a bit hand-wavy but maybe that's the best we can do for now. FWIW Chrome right now does not implement this logic (i.e. all events dispatched go through the event dispatching logic), but we may want to do so in the future. Given that this section has been confusing for a few folks, I'm debating whether to change it a lot (as per your suggestion) or to remove it for now.

**Comment by npm1** [comment]
Looks like this got fixed at some point. I don't see any "Queuing other entries" or "create an event timing entry" and what remains is a Note:

`Note: If a user agent skips the event dispatch algorithm, it can still choose to include an entry for that Event. In this case, it will estimate the value of processingStart and set the processingEnd to the same value.`

Zero is also not being misused as before in the spec. So I'll close this but let me know if I missed something.
