### ISSUE TITLE
Formatting/style nits

### ISSUE THREAD

**Issue by domenic** [WICG/event-timing#35]
In the introduction and security & privacy sections, performance.now() should be in code font. (You should be able to use Bikeshed syntax like `{{Performance/now()|performance.now()}}` if the links metadata is set up right).

---

"javascript" should be "JavaScript"

---

"event timing API" is inconsistently cased, sometimes titlecase, sometimes lowercase.

---

Event names should be in code font. (Bikeshed should be able to do `{{keydown}}`, but it might need a prefix depending on how the source spec is set up...)

---

Section titles are almost all sentence case (good) except for "Usage Example".

---

Inconsistent spacing between numbers and the unit suffix "ms". I personally prefer `&nbsp;`, but I think no-space is more prevalent on the platform. I don't think it matters much but you might as well be consistent within the document.

---

> \<type, num-events\>

I would phrase this as _type_ → _num-events_. Although it isn't talking about an [Infra map](https://infra.spec.whatwg.org/#maps), the syntax might be more familiar.

---

> Invoke the algorithm to initialize event timing passing event and the current high resolution time as inputs. Let timingEntry be the output.

I would phrase this as

> Let _timingEntry_ be the result of initializing event timing, given event and the current high resolution time.

(similar for the finalize event timing invocation).

----

We don't usually code-font boolean literals or null.

---

The camel-case names pendingEventEntries, pendingPointerDown, and hasDispatchedEvent are unconventional. Usually we'd use "pending event entries", etc., for these sort of internal slot names. (Camel case is used for variable names, though.)

---

We usually don't put the quotation marks for strings inside the code. So `` "`foo`" ``, not `` `"foo"` ``.

But, for event names, we usually don't use quotes at all, instead cross-linking them with `{{pointermove}}` or similar.

---

We're using "return" instead of "abort these steps" these days.

---

In "dispatch pending entries", you use "Queue" then "Queue the entry", but they are the same thing. Better to pick one and be consistent.

---

> To create an event timing entry 

This should be a dfn, not just italicized, right?

**Comment by npm1** [comment]
> Event names should be in code font. (Bikeshed should be able to do `{{keydown}}`, but it might need a prefix depending on how the source spec is set up...)

How can they work with "{{", if they are defined with dfn? These are just event types.

> We don't usually code-font boolean literals or null.

Fine, though I'll say that code-font emphasizes the booleans nicely as it adds red color to the text.

> We usually don't put the quotation marks for strings inside the code. So `` "`foo`" ``, not `` `"foo"` ``.

Similarly, that's fine, but code-font sets strings to yellow, which is nicer format.

> This should be a dfn, not just italicized, right?

Ah yes, I think I use `<em>` because it complained about it not being used. Exporting it fixes the problem.

**Comment by domenic** [comment]
> How can they work with "{{", if they are defined with dfn? These are just event types.

I think this should work:

```html
<dfn event for="SomeInterface">eventname</dfn>

{{SomeInterface/eventname}}
```

For the strings and boolean literals, please feel free to use your own style in your own spec; I don't feel strongly :).

**Comment by npm1** [comment]
So I'm guessing that would require a change in the spec where those events are defined? Or is there some easier way to achieve this?

UIEvents spec is mostly written in ReSpec, do we also have fancy integrations of ReSpec definitions in bikeshed?

**Comment by domenic** [comment]
No, ReSpec does not play well, sadly. But, you can just change https://github.com/WICG/event-timing/blob/cc3761cd9116485deaa4fae681428ee79377e978/index.bs#L69 from `type: dfn` to `type: event`, and add a `for` (maybe `Element`, I dunno), and then it will work in your spec.
