### ISSUE TITLE
Event Timing spec is up!

### ISSUE THREAD

**Issue by npm1** [WICG/event-timing#47]
FYI this is the Event Timing spec which we have on incubation. Eventually the idea is to move over to W3C so feedback is welcome!
@rniwa @mstange @bzbarsky @toddreifsteck @yoavweiss

**Comment by bzbarsky** [comment]
@smaug----

**Comment by zhouqicf** [comment]
Trial for EventTiming is complete, will chrome officially support this feature in the next version?

**Comment by npm1** [comment]
Chrome plans to ship First Input Timing on 77, don't have a time for full Event Timing yet.
