### ISSUE TITLE
"Approximate the 75'th percentile of click event queueing times." as a use case does not make sense

### ISSUE THREAD

**Issue by smaug----** [WICG/event-timing#48]
Click event is dispatched as a reaction to mousedown/up, so there shouldn't be really queuing.

**Comment by npm1** [comment]
I can change it to mousedown. But I'd define the queueing time of a click event as the delta between the click event processingStart and the hardware timestamp (when the user clicked). Does that make sense?

**Comment by smaug----** [comment]
What is "when user clicked"? click is DOM thingie, created based on mousedown/up, or tap, or keypress (enter key)

**Comment by npm1** [comment]
> What is "when user clicked"? click is DOM thingie, created based on mousedown/up, or tap, or keypress (enter key)

Yes, and those are created based on user gestures, so the Event timeStamp for those is 'when the user clicked'.

**Comment by npm1** [comment]
We define the queueing time of an event as the processingStart - startTime of the associated PerformanceElementTiming entry. Though maybe for click events this is not something super useful, so I think I'll change the event type in the example.

**Comment by npm1** [comment]
@smaug---- can this now be closed?

**Comment by smaug----** [comment]
User doesn't "click" when using mouse. There is mousedown and up. But ok, if example is changed, then this can be changed.
