### ISSUE TITLE
Set baseline of 100ms for duration

### ISSUE THREAD

**Issue by hawkinsw** [WICG/event-timing#57]
I see in the Security section that there is a reference to a lower bound on the duration value of a timing entry. However, I do not see that specified as a requirement in the spec. I am sure that I am missing it. Could you point it out to me? 

Thank you!

**Comment by npm1** [comment]
It is in the processing model:

> If timingEntry’s duration attribute value is greater than or equal to 104, then queue timingEntry.

It is also mentioned in the security considerations section:

> The choice of 104ms as the cutoff value for the duration is just the first multiple of 8 greater than 100ms

Does that make sense?

**Comment by hawkinsw** [comment]
> It is in the processing model:
> 
> > If timingEntry’s duration attribute value is greater than or equal to 104, then queue timingEntry.
> 

I completely missed this; I am so sorry for the SPAM.

> It is also mentioned in the security considerations section:
> 
> > The choice of 104ms as the cutoff value for the duration is just the first multiple of 8 greater than 100ms
> 

I saw this but since it was part of the "explanation" and not part of the spec, I didn't think it was enough. Now that I see the above reference to 104, I am absolutely satisfied. Again, sorry for the SPAM!

Will

> Does that make sense?

**Comment by npm1** [comment]
No need to apologize at all! Closing this issue
