### ISSUE TITLE
It is totally unclear what 'duration' tries to measure

### ISSUE THREAD

**Issue by smaug----** [WICG/event-timing#6]
remember, 'Update the rendering' (step 7) is end-of-task model, not the time when UA actually updates rendering.
And because of that it is unclear what the proposal is about.

**Comment by tdresser** [comment]
I've cleared this up [here](https://github.com/WICG/event-timing/commit/73925482029e1b300770d8e9ec00cd05ee2b4494).

This now aligns fairly closely with the paint timing spec [here](https://w3c.github.io/paint-timing/#mod).

Aside, we should get rid of the monkey patching in paint timing, filed an issue [here](https://github.com/w3c/paint-timing/issues/30).

Does this look reasonable to you?

**Comment by smaug----** [comment]
That looks better. It is still unclear to me what one actually tries to measure with 'duration' or why.
One can easily get mousemove events which don't cause any changes to the layout, so the next rendering update may happen seconds later.

**Comment by tdresser** [comment]
My reading of the spec is that we "update the rendering" even when there's no visible update.
The spec doesn't try to early out of that step. A user agent may choose to implement a fast path, in which case they will need to populate |duration| in such a way that it's consistent whether or not a visual update occurred.

Does that make sense to you?

**Comment by annevk** [comment]
Step 3 and step 4 of "update the rendering" allow you to end up with no documents to update so that doesn't seem entirely accurate.

**Comment by tdresser** [comment]
Yikes - not sure how I missed that, thanks.

I'll have to give some thought to how to address this.

**Comment by npm1** [comment]
@tdresser can we consider this fixed?

**Comment by tdresser** [comment]
Yup, I think so. @smaug, feel free to reopen if you think there's additional work to be done here.

**Comment by smaug----** [comment]
Wrong smaug ;) But looking.
