### ISSUE TITLE
"nearest multiple of 8" in "dispatch pending Event Timing entries" must specify the unit

### ISSUE THREAD

**Issue by rniwa** [WICG/event-timing#68]
The concept to [dispatch pending Event Timing entries](https://wicg.github.io/event-timing/#dispatch-pending-event-timing-entries) has the following steps:

>  - Let difference be `renderingTimestamp - start`.
> - Set timingEntry’s duration to the result of rounding difference to the nearest multiple of 8.

It's totally unclear what the nearest multiple of 8 means in this context because the spec doesn't specify the unit.

**Comment by rniwa** [comment]
This is also not safe in terms of Spectre protection. Without going into details of why, I suggest rephrasing this to just say that the user agent is required to reduce the time resolution to be less than 8ms.

**Comment by npm1** [comment]
Ok, I created a PR to address the units issue. I'm not sure what the second comment refers to though. I didn't see Spectre being mentioned in the spec. Is the suggestion to make the rounding more vague so a user agent can choose a granularity of, say, 20ms instead of 8ms?

**Comment by rniwa** [comment]
No, you can't compute the difference then around it. That's not safe.

**Comment by rniwa** [comment]
https://github.com/WICG/event-timing/pull/70 didn't fix this issue.

**Comment by npm1** [comment]
> No, you can't compute the difference then round it. That's not safe.

Can you elaborate? What do you propose instead? Adding jitter?

**Comment by rniwa** [comment]
> > No, you can't compute the difference then round it. That's not safe.
> 
> Can you elaborate? What do you propose instead? Adding jitter?

I suggest we simply state that precision needs to be 8ms or less like this:

> Let difference be renderingTimestamp - start with less than 8ms granularity.
