### ISSUE TITLE
Event's delay is rather vague

### ISSUE THREAD

**Issue by smaug----** [WICG/event-timing#90]
https://wicg.github.io/event-timing/#event-delay
is rather vague since it isn't always clear to what point in time event's timestamp refers to.

**Comment by npm1** [comment]
I don't follow, event's timestamp is linking to https://dom.spec.whatwg.org/#dom-event-timestamp which is the value we use. What's vague about that?

**Comment by smaug----** [comment]
For example click event's timestamp, what it is pointing to? Click event is dispatched (not only) as a reaction to mousedown + mouseup. So if timestamp of click is created when the event is created, timestamp would point to time just before dispatching the event , which is the same as "the time when the browser is about to run event handlers for the event". So delay would be always 0.
But click might get its timestamp from mouseup too.
Similar issue applies to all the events which aren't truly user input, but are reaction to something:
mouseover (reaction to mousemove causing cursor to move to be over a new element), mouseout, mouseenter, mouseleave,
similar pointer* events,  etc.

And now that I think it "the time when the browser is about to run event handlers for the event" isn't very clear either.
When is that "about to run event handlers". It is right before running any event listeners (note, event listeners, not event handlers. Event handlers are a subset of event listeners), but at which point? Right after creating the event path? Or just before https://dom.spec.whatwg.org/#concept-event-dispatch is called?

**Comment by npm1** [comment]
We do use the event's timeStamp in the implementation, which probably isn't what we want in the long term for 'artificial' input events. This would probably require a lot of work in the input specs, as it would probably require fixing it on a case-by-case basis. For now, the timeStamp is the closest point in time we have to when the user interaction occurred, but it's not perfect.

You're right that the time when we're 'about to run event handlers' is not that precise. I'm tempted to mark that part of the section non-normative (starting from definition of delay). We can clarify there that delay is computed as processingStart - startTime, and processingStart is set in the processing model (so the answer is the latter, the beginning of https://dom.spec.whatwg.org/#concept-event-dispatch).

**Comment by smaug----** [comment]
But what is the timestamp? When is the timestamp created? Like, perhaps you get timestamp from the OS for some events, but not for some others? That all is very unclear how it should behave.

**Comment by npm1** [comment]
We use the timeStamp attribute value https://dom.spec.whatwg.org/#dom-event-timestamp. I don't think the answer to that is in the scope of this specification, so questions about that would go in DOM.

**Comment by smaug----** [comment]
But the API isn't particularly useful if implementations may return 0 or some other delay.
I would expect many of the events use the timestamp when they are created, meaning that delay would be often 0.

**Comment by npm1** [comment]
Yea, this is a problem for events that are not tied to hardware timestamps, such as click.

**Comment by npm1** [comment]
We'd like to fix the timeStamp setting in https://dom.spec.whatwg.org/#inner-event-creation-steps since HR Time already provides the methods to set it accurately

**Comment by npm1** [comment]
The above has been fixed in the DOM spec.
