### ISSUE TITLE
toJSON() shouldn't include target attribute

### ISSUE THREAD

**Issue by sefeng211** [WICG/event-timing#97]
The `target` attribute has a `Node?` type, which falls under [nullable types whose inner type is a JSON type](https://heycam.github.io/webidl/#dfn-json-types), and the inner type is `Node` which is a `interface type`. According to the webidl spec, we should only include it if it `has a toJSON operation declared on themselves or one of their inherited interfaces`. And I don't think `Node` qualifies it. 

However, the [toJSON test](https://github.com/web-platform-tests/wpt/blob/master/event-timing/toJSON.html#L30) expects it to exist, and the API indeed has this attribute included. 

Please let me know if I misunderstood anything.

**Comment by npm1** [comment]
That sounds right, thanks for pointing this out!

**Comment by npm1** [comment]
Ok, test change has landed, so closing. Let me know if I missed something.
